-- Harbour v1 initial schema.
--
-- Read this before changing anything below.
--
-- 1. THERE ARE TWO SIDES, AND THEY ARE SYMMETRIC. The earlier trial repo
--    (devanshgautam2005-cmyk/harbor) was built on ADR-007: the parent installs
--    nothing and has no account. The UI has since grown a full parent mode --
--    a parent's own day, seeds they plant, their child's weather over their
--    field -- and none of that can work one-sided. So both sides hold an
--    account here and the old ADR is superseded. What is NOT superseded is the
--    reason behind it: a link must be mutual, and it must expose the narrowest
--    thing that makes the feature work.
--
-- 2. A LINK IS MUTUAL OR IT DOES NOT EXIST. Everything readable across the
--    pair goes through harbour_linked(), which is true only when BOTH people
--    hold a contact row pointing at the other. Nobody can read their way into
--    somebody's day by inserting a row on their own side.
--
-- 3. THE PROMISES IN THE UI ARE ENFORCED HERE, NOT JUST DRAWN.
--    "They see the gaps, never what is in them" -- the busy_blocks table is
--    owner-only and the counterpart reads shared_busy, a view with no label
--    column. The label cannot be selected across the link because it is not in
--    the relation they are allowed to read.
--    "They are never told when it will open" -- a seed row is invisible to its
--    recipient until bloom_at has passed. Not hidden by the client: not
--    returned by the database.
--
-- 4. Ids are generated by the device so an offline phone can write its whole
--    backlog and retry with a plain upsert.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- enums

create type harbour_mode    as enum ('student', 'parent');
create type harbour_weather as enum ('clear', 'bright', 'cloudy', 'rain', 'storm');
create type note_scope      as enum ('personal', 'shared');
create type flower_kind     as enum ('daisy', 'tulip', 'poppy', 'cosmos',
                                     'marigold', 'bluebell', 'aster', 'sunflower');
create type moment_kind     as enum ('called', 'reacted', 'proposed_later',
                                     'message', 'dismissed', 'played');
create type puzzle_id       as enum ('sudoku', 'zip', 'tango');

-- ------------------------------------------------------------- profiles
-- One row per account. Everything here except the four columns exposed by
-- shared_profiles is private to its owner.

create table profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  display_name  text not null default '',
  mode          harbour_mode not null default 'student',
  setup_done    boolean not null default false,
  -- Which sides of the phone this person has already been walked through.
  tours_seen    harbour_mode[] not null default '{}',

  -- How their week is going. On a parent's field this is their CHILD's sky,
  -- which is why it has to cross the link at all.
  weather       harbour_weather not null default 'bright',
  weather_at    timestamptz not null default now(),
  -- Whose sky the field shows, when more than one person is linked.
  watching      uuid references auth.users (id) on delete set null,

  -- Typed down a phone line by whoever is joining you. Unique, and rotatable.
  invite_code   text not null unique,

  milestone_title text,
  milestone_date  date,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- --------------------------------------------------------- user_settings
-- Ranges match the prototype's settings form, so a value the UI accepts cannot
-- be rejected here, or the reverse.

create table user_settings (
  user_id          uuid primary key references auth.users (id) on delete cascade,
  cues_enabled     boolean not null default false,
  walking_minutes  integer not null default 10  check (walking_minutes  between 1 and 120),
  daily_cap        integer not null default 2   check (daily_cap        between 1 and 10),
  cooldown_minutes integer not null default 120 check (cooldown_minutes between 1 and 1440),
  sound            text    not null default 'chime' check (sound in ('chime', 'soft', 'silent')),
  reduced_motion   boolean not null default false,
  theme            text    not null default 'light' check (theme in ('system', 'light', 'dark')),
  -- Sharing your week is opt-in on both sides, exactly as the UI asks.
  sharing          boolean not null default false,
  updated_at       timestamptz not null default now()
);

-- ------------------------------------------------------------- contacts
-- A row on your list. linked_user_id is null for somebody who has not joined
-- yet: they still show on the list, they just have nothing to send back.

create table contacts (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users (id) on delete cascade,
  linked_user_id uuid references auth.users (id) on delete set null,
  label          text not null,
  tone           text not null default 'green' check (tone in ('green', 'gold', 'orange', 'sky')),
  phone_e164     text check (phone_e164 ~ '^\+[1-9]\d{7,14}$'),
  created_at     timestamptz not null default now(),

  -- One row per person on your list, and you cannot add yourself.
  constraint contact_is_not_self check (user_id <> linked_user_id),
  unique (user_id, linked_user_id)
);

create index contacts_user_idx   on contacts (user_id);
create index contacts_linked_idx on contacts (linked_user_id);

-- -------------------------------------------------------- the link test
-- True only when both sides hold a contact row pointing at the other. Every
-- cross-account policy in this file goes through it.
--
-- security definer so the check itself can see both rows: a viewer cannot read
-- the counterpart's contacts table, and without this the test would be decided
-- by what the viewer happens to be allowed to see.

create function harbour_linked(viewer uuid, subject uuid)
returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1
      from contacts mine
      join contacts theirs
        on theirs.user_id = subject and theirs.linked_user_id = viewer
     where mine.user_id = viewer and mine.linked_user_id = subject
  );
$$;

-- ----------------------------------------------------------- busy_blocks
-- Your own day. The label is yours alone; see note 3 at the top.

create table busy_blocks (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  day        date not null,
  starts_at  time not null,
  ends_at    time not null,
  label      text,
  -- Came from a connected calendar rather than being marked by hand.
  linked     boolean not null default false,
  created_at timestamptz not null default now(),

  constraint block_ends_after_it_starts check (starts_at < ends_at)
);

create index busy_blocks_user_day_idx on busy_blocks (user_id, day);

-- What the other side of a link is allowed to see: when you are busy, never
-- what you are doing. security_invoker so the caller's own RLS still applies.
create view shared_busy
  with (security_invoker = true) as
  select id, user_id, day, starts_at, ends_at
    from busy_blocks;

-- Same shape for profiles: a name and a sky, nothing else.
create view shared_profiles
  with (security_invoker = true) as
  select id, display_name, weather, weather_at
    from profiles;

-- ---------------------------------------------------------------- plans
-- Something you told your people you are doing. Unlike a busy block, a plan is
-- meant to be read, label and all -- that is the point of sharing it.

create table plans (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  day        date not null,
  starts_at  time not null,
  ends_at    time not null,
  label      text not null,
  created_at timestamptz not null default now(),

  constraint plan_ends_after_it_starts check (starts_at < ends_at)
);

create index plans_user_day_idx on plans (user_id, day);

-- ---------------------------------------------------------------- notes
-- personal: for one person. shared: for everyone you are linked to.

create table notes (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,
  -- Set for a personal note, null for one addressed to everybody.
  audience_id uuid references auth.users (id) on delete cascade,
  scope       note_scope not null,
  body        text not null check (length(body) <= 2000),
  flower      flower_kind,
  at          timestamptz not null default now(),

  constraint personal_notes_have_an_audience
    check ((scope = 'personal') = (audience_id is not null))
);

create index notes_user_idx     on notes (user_id, at desc);
create index notes_audience_idx on notes (audience_id, at desc);

-- ---------------------------------------------------------------- seeds
-- A note planted now for a flower that opens later. The recipient cannot read
-- the row at all until it blooms -- see note 3.

create table seeds (
  id         uuid primary key default gen_random_uuid(),
  from_id    uuid not null references auth.users (id) on delete cascade,
  to_id      uuid not null references auth.users (id) on delete cascade,
  flower     flower_kind not null,
  body       text not null check (length(body) <= 2000),
  planted_at timestamptz not null default now(),
  bloom_at   timestamptz not null,

  constraint a_seed_goes_to_somebody_else check (from_id <> to_id),
  constraint a_seed_opens_after_it_is_planted check (bloom_at > planted_at)
);

create index seeds_to_idx   on seeds (to_id, bloom_at);
create index seeds_from_idx on seeds (from_id, bloom_at);

-- ------------------------------------------------------------- messages
-- One thread per pair. Voice notes carry the recording's storage path and the
-- transcript the sender read back and kept or corrected.

create table messages (
  id        uuid primary key default gen_random_uuid(),
  from_id   uuid not null references auth.users (id) on delete cascade,
  to_id     uuid not null references auth.users (id) on delete cascade,
  body      text not null default '',
  voice_path    text,
  voice_seconds integer check (voice_seconds is null or voice_seconds >= 0),
  voice_edited  boolean not null default false,
  liked     boolean not null default false,
  at        timestamptz not null default now(),

  constraint a_message_goes_to_somebody_else check (from_id <> to_id)
);

create index messages_pair_idx on messages (from_id, to_id, at desc);
create index messages_to_idx   on messages (to_id, at desc);

-- ---------------------------------------------------------------- snaps
-- One picture, taken now rather than chosen.

create table snaps (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  media_path text,
  caption    text check (caption is null or length(caption) <= 280),
  prompt_day date,
  at         timestamptz not null default now()
);

create index snaps_user_idx on snaps (user_id, at desc);

-- -------------------------------------------------------------- moments
-- What a call became. Private: this is the user's own record of their calling,
-- and the flowers in their field are grown from it.

create table moments (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  contact_id uuid references contacts (id) on delete set null,
  kind       moment_kind not null,
  body       text not null default '',
  minutes    integer check (minutes is null or minutes >= 0),
  feeling    text check (feeling is null or feeling in ('light', 'warm', 'steady', 'tender')),
  flower     flower_kind,
  topic      text,
  at         timestamptz not null default now()
);

create index moments_user_idx on moments (user_id, at desc);

-- ------------------------------------------------------- puzzle_results
-- Only finished puzzles are recorded, so a row is always a win. Readable
-- across a link because the leaderboard is the whole point of them.

create table puzzle_results (
  user_id uuid not null references auth.users (id) on delete cascade,
  day     date not null,
  puzzle  puzzle_id not null,
  seconds integer not null check (seconds >= 0),
  at      timestamptz not null default now(),
  primary key (user_id, day, puzzle)
);

-- --------------------------------------------------------- daily_answers
-- One line each, from everybody at home.

create table daily_answers (
  user_id uuid not null references auth.users (id) on delete cascade,
  day     date not null,
  body    text not null check (length(body) <= 500),
  at      timestamptz not null default now(),
  primary key (user_id, day)
);

-- ------------------------------------------------------------------ RLS

alter table profiles       enable row level security;
alter table user_settings  enable row level security;
alter table contacts       enable row level security;
alter table busy_blocks    enable row level security;
alter table plans          enable row level security;
alter table notes          enable row level security;
alter table seeds          enable row level security;
alter table messages       enable row level security;
alter table snaps          enable row level security;
alter table moments        enable row level security;
alter table puzzle_results enable row level security;
alter table daily_answers  enable row level security;

-- auth.uid() is wrapped in a scalar subquery throughout so the planner runs it
-- once per statement rather than once per row.

-- profiles: yours to write; a linked person may read (the views narrow what
-- that means in practice, and nothing sensitive lives here anyway).
create policy "read own profile"    on profiles for select
  using ((select auth.uid()) = id or harbour_linked((select auth.uid()), id));
create policy "write own profile"   on profiles for update
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "insert own profile"  on profiles for insert
  with check ((select auth.uid()) = id);

create policy "own settings" on user_settings for all
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "own contacts" on contacts for all
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- The day: yours to write, and readable by a linked person only when you have
-- turned sharing on. shared_busy is what they actually select from.
create policy "own busy blocks" on busy_blocks for all
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "linked can read busy times" on busy_blocks for select
  using (
    harbour_linked((select auth.uid()), user_id)
    and exists (select 1 from user_settings s where s.user_id = busy_blocks.user_id and s.sharing)
  );

create policy "own plans" on plans for all
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "linked can read plans" on plans for select
  using (harbour_linked((select auth.uid()), user_id));

-- A personal note is for exactly one person; a shared one for everyone linked.
create policy "own notes" on notes for all
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "notes addressed to me" on notes for select
  using (
    case when scope = 'personal'
      then audience_id = (select auth.uid())
      else harbour_linked((select auth.uid()), user_id)
    end
  );

-- The seed rule, and the reason this table is worth its own policy: the
-- recipient cannot see the row -- not the flower, not the text, not that it
-- exists -- until the moment it opens.
create policy "seeds you planted" on seeds for all
  using ((select auth.uid()) = from_id) with check ((select auth.uid()) = from_id);
create policy "seeds that have opened for me" on seeds for select
  using ((select auth.uid()) = to_id and bloom_at <= now());

create policy "messages in my threads" on messages for select
  using ((select auth.uid()) in (from_id, to_id));
create policy "send my own messages" on messages for insert
  with check ((select auth.uid()) = from_id and harbour_linked((select auth.uid()), to_id));
-- Either side may like a message; only the sender may delete one.
create policy "update messages in my threads" on messages for update
  using ((select auth.uid()) in (from_id, to_id)) with check ((select auth.uid()) in (from_id, to_id));
create policy "delete my own messages" on messages for delete
  using ((select auth.uid()) = from_id);

create policy "own snaps" on snaps for all
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "linked can read snaps" on snaps for select
  using (harbour_linked((select auth.uid()), user_id));

create policy "own moments" on moments for all
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "own puzzle results" on puzzle_results for all
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "linked can read puzzle results" on puzzle_results for select
  using (harbour_linked((select auth.uid()), user_id));

create policy "own daily answer" on daily_answers for all
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "linked can read daily answers" on daily_answers for select
  using (harbour_linked((select auth.uid()), user_id));

-- -------------------------------------------------------------- invites
-- A code somebody can read down a phone line without spelling it out: three
-- letters that cannot be mistaken for each other, then four digits.

create function harbour_new_invite_code() returns text
language plpgsql volatile as $$
declare
  letters constant text := 'ACDEFGHJKLMNPRTUVWXY';
  code text;
begin
  loop
    code := substr(letters, 1 + floor(random() * 20)::int, 1)
         || substr(letters, 1 + floor(random() * 20)::int, 1)
         || substr(letters, 1 + floor(random() * 20)::int, 1)
         || '-' || lpad((1000 + floor(random() * 9000))::int::text, 4, '0');
    exit when not exists (select 1 from profiles where invite_code = code);
  end loop;
  return code;
end;
$$;

-- Joining somebody. Writes BOTH contact rows in one transaction, because a
-- half-made link is exactly the state harbour_linked() is designed to reject
-- and there is no screen anywhere that could repair it.
create function redeem_invite(code text, my_label text default null)
returns uuid
language plpgsql volatile security definer set search_path = public as $$
declare
  me    uuid := auth.uid();
  host  profiles;
begin
  if me is null then
    raise exception 'not signed in' using errcode = '28000';
  end if;

  select * into host from profiles p where p.invite_code = upper(trim(code));
  if host is null then
    raise exception 'that code does not belong to anybody' using errcode = 'P0002';
  end if;
  if host.id = me then
    raise exception 'that is your own code' using errcode = 'P0001';
  end if;

  insert into contacts (user_id, linked_user_id, label)
    values (me, host.id, coalesce(host.display_name, 'Them'))
    on conflict (user_id, linked_user_id) do update set label = excluded.label;

  insert into contacts (user_id, linked_user_id, label)
    values (host.id, me, coalesce(my_label, (select display_name from profiles where id = me), 'Them'))
    on conflict (user_id, linked_user_id) do update set label = excluded.label;

  return host.id;
end;
$$;

revoke all on function redeem_invite(text, text) from public;
grant execute on function redeem_invite(text, text) to authenticated;

-- ------------------------------------------------------------- triggers
-- A new account gets a profile and a settings row, so the app never has to
-- handle a missing-settings state on first run.

create function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into profiles (id, display_name, invite_code)
    values (new.id,
            coalesce(new.raw_user_meta_data ->> 'display_name', ''),
            harbour_new_invite_code());
  insert into user_settings (user_id) values (new.id);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

create function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_touch      before update on profiles
  for each row execute function touch_updated_at();
create trigger user_settings_touch before update on user_settings
  for each row execute function touch_updated_at();
